[package]
name = "matrices"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
num = "0.4.3"
pretty_env_logger = "0.5.0"
rayon = "1.10.0"
validator = { version = "0.18.1", features = ["derive"] }

[profile.release]
opt-level = 0
debug = true
